dependencies:
  override:
    - mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline

test:
  override:
    - mvn -o surefire:test

deployment:
  main:
    branch: master
    commands:
      - mvn clean package #-s .circleci.settings.xml -DskipTests deploy