version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - unit-test
      - publish-docker:
          requires:
            - unit-test
      - deploy:
          requires:
            - publish-docker
          filters:
            branches:
              only: master

jobs:
  unit-test:
    docker:
      - image: codeaches/openjdk:12-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - pawnshop-report-{{ checksum "pom.xml" }}
            - pawnshop-report
      - run: mvn dependency:go-offline
      - run:
          name: Build and unit test
          command: |
            mvn test -B \
              -Dbuild.number=${CIRCLE_BUILD_NUM} \
              -Dcommit.hash=${CIRCLE_SHA1} \
              -Dcircle.workflow.guid=${CIRCLE_WORKFLOW_ID} \
              -Dbuild.user=${CIRCLE_PROJECT_USERNAME} \
              -Dbuild.repo=${CIRCLE_PROJECT_REPONAME}
      - save_cache:
          paths:
            - ~/.m2
          key: pawnshop-report-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports



  publish-docker:
    docker:
      - image: codeaches/openjdk:12-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - pawnshop-report-{{ checksum "pom.xml" }}
            - pawnshop-report
      - run: mvn dependency:go-offline
      - run: cp ./settings.xml ~/.m2/settings.xml
      - run: echo "<settingsSecurity><master>${maven_security_master}</master></settingsSecurity>" > ~/.m2/settings-security.xml
      - run:
          name: Publish Docker image with Jib
          command: |
            mvn compile jib:build -B -DskipTests=true \
              -Dbuild.number=${CIRCLE_BUILD_NUM} \
              -Dcommit.hash=${CIRCLE_SHA1} \
              -Dcircle.workflow.guid=${CIRCLE_WORKFLOW_ID} \
              -Dbuild.user=${CIRCLE_PROJECT_USERNAME} \
              -Dbuild.repo=${CIRCLE_PROJECT_REPONAME}

  deploy:
    machine:
      enabled: true
      steps:
        - add_ssh_keys:
            fingerprints:
              - "bf:fa:d5:bd:b5:37:8b:ff:58:0d:51:1a:27:97:84:4b"
        - run:
            name: Deploy Over SSH
            command: |
              ssh root@77.244.214.183 "dc pull && dc down && dc up -d"
